default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: root
  # password: password # デフォルトだと空欄になっているはずなので変更
  # host: db # デフォルトだとlocalhostになっているはずなので変更

development:
  <<: *default
  host: db # デフォルトだとlocalhostになっているはずなので変更
  database: vacansee_development
  username: root
  password: password # デフォルトだと空欄になっているはずなので変更

test:
  <<: *default
  database: vacansee_test

production:
  <<: *default
  # host: vacanseedb.ct1g5h2by98v.ap-northeast-1.rds.amazonaws.com
  # database: vacanseedb
  # username: dbmaster
  # password: G9qWklHuyWoiLz0NrR56
  host: <%= ENV["DATABASE_HOST"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
